apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ${{ steps.login-ecr.outputs.registry }}/instagram-server:latest
  newName: ${{ steps.login-ecr.outputs.registry }}/instagram-server:latest
  newTag: abcdefg
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
